# Generated by Django 5.0.2 on 2024-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0002_remove_backlink_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="backlink",
            name="type",
            field=models.CharField(
                choices=[("BlogSeri1", "BlogSeri1"), ("WpPostYorum", "WpPostYorum")],
                default=1,
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
