# Generated by Django 5.0.2 on 2024-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0003_backlink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backlink",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("BlogSeri1", "BlogSeri1"), ("WpPostYorum", "WpPostYorum")],
                max_length=40,
            ),
        ),
    ]
