# Generated by Django 5.0.2 on 2024-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0004_alter_backlink_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainbacklink",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beklemede", "Beklemede"),
                    ("işlemde", "işlemde"),
                    ("OK", "OK"),
                ],
                max_length=40,
            ),
        ),
    ]
