# Generated by Django 5.0.2 on 2024-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0005_domainbacklink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain", name="name", field=models.URLField(),
        ),
    ]
