# Generated by Django 5.0.2 on 2024-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0006_alter_domain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain", name="Blogconten", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="domain", name="Yazar", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="domain", name="Yorum", field=models.TextField(blank=True),
        ),
    ]
