# Generated by Django 5.0.2 on 2024-02-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0007_domain_blogconten_domain_yazar_domain_yorum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain", old_name="Blogconten", new_name="Blogcontent",
        ),
    ]
