# Generated by Django 5.0.2 on 2024-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0008_rename_blogconten_domain_blogcontent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain", old_name="Yazar", new_name="BlogTitle",
        ),
        migrations.AddField(
            model_name="domain", name="YorumYazar", field=models.TextField(blank=True),
        ),
    ]
