# Generated by Django 5.0.2 on 2024-02-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0010_backlink_guncelleme_tarihi_backlink_olusturma_tarihi_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domainbacklink", old_name="type", new_name="Durum",
        ),
    ]
