# Generated by Django 5.0.2 on 2024-02-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0011_rename_type_domainbacklink_durum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain", old_name="name", new_name="domain",
        ),
        migrations.AddField(
            model_name="domain",
            name="sahiplik",
            field=models.CharField(
                blank=True,
                choices=[("Bizim", "Bizim"), ("Müşteri", "Müşteri")],
                max_length=40,
            ),
        ),
    ]
