# Generated by Django 5.0.2 on 2024-04-04 23:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0013_mahsul_postkategori_kontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="kontrol",
            name="icerikNew",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
