# Generated by Django 5.0.2 on 2024-04-04 23:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0014_kontrol_iceriknew"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontrol", name="icerikNew",),
        migrations.AddField(
            model_name="kontrol",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
