# Generated by Django 5.0.2 on 2024-04-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0015_remove_kontrol_iceriknew_kontrol_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backlink", options={"verbose_name_plural": "1-Backlink"},
        ),
        migrations.AlterModelOptions(
            name="domain", options={"verbose_name_plural": "1-Domain"},
        ),
        migrations.AlterModelOptions(
            name="domainbacklink", options={"verbose_name_plural": "1-DomainBacklink"},
        ),
        migrations.AlterModelOptions(
            name="kontrol", options={"verbose_name_plural": "2-Kontrol"},
        ),
        migrations.AlterModelOptions(
            name="mahsul", options={"verbose_name_plural": "2-Mahsuller"},
        ),
        migrations.AlterModelOptions(
            name="postkategori", options={"verbose_name_plural": "2-Post Kategori"},
        ),
        migrations.AddField(
            model_name="kontrol",
            name="cocukmasali",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="kidsStories",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="yuksekteknoloji",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kontrol",
            name="Akibeti",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kullan", "Kullan"),
                    ("Salla", "Salla"),
                    ("Beklemede", "Beklemede"),
                    ("Tamamlandi", "Tamamlandi"),
                    ("Hazirla", "Hazirla"),
                    ("Yolda", "Yolda"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kontrol",
            name="Kaynak_Dili",
            field=models.CharField(
                blank=True,
                choices=[("ENG", "ENG"), ("TR", "TR"), ("De", "DE")],
                max_length=255,
                null=True,
            ),
        ),
    ]
