# Generated by Django 5.0.2 on 2024-04-28 23:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seo", "0016_alter_backlink_options_alter_domain_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kontrol",
            name="ailerehberi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="annebak",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="bayanlaraozel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="ekli",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="hamilelik",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="icerik2",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="icerik3",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="icerik4",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="icerik5",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="kadinlaricin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="kadinsorunlari",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="kadinvehayat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="makyajvemoda",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="siteniz",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kontrol",
            name="tiklahadi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kontrol", "Kontrol"),
                    ("Kullan", "Kullan"),
                    ("Kullanıldı", "Kullanıldı"),
                    ("Kullanma", "Kullanma"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
